[2025-11-01T17:04:26.049+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T17:04:24.083539+00:00 [queued]>
[2025-11-01T17:04:26.074+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T17:04:24.083539+00:00 [queued]>
[2025-11-01T17:04:26.075+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T17:04:26.096+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_merchants> on 2025-11-01 17:04:24.083539+00:00
[2025-11-01T17:04:26.102+0000] {standard_task_runner.py:60} INFO - Started process 1094 to run task
[2025-11-01T17:04:26.108+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_merchants', 'manual__2025-11-01T17:04:24.083539+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp4w4ax2hg']
[2025-11-01T17:04:26.114+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask dbt_run_merchants
[2025-11-01T17:04:26.217+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T17:04:24.083539+00:00 [running]> on host 69cecc54c654
[2025-11-01T17:04:26.338+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T17:04:24.083539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T17:04:24.083539+00:00'
[2025-11-01T17:04:30.885+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 184, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_merchants", ds=ds, full_refresh=True, pass_ds_lagged=False),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (2).
STDOUT:
17:04:28  Running with dbt=1.5.9
17:04:29  Registered adapter: clickhouse=1.5.2
17:04:29  Unable to do partial parsing because config vars, config profile, or config target have changed
17:04:30  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 2
      config(


STDERR:

[2025-11-01T17:04:30.904+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_merchants, execution_date=20251101T170424, start_date=20251101T170426, end_date=20251101T170430
[2025-11-01T17:04:30.919+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task dbt_run_merchants (dbt failed (2).
STDOUT:
17:04:28  Running with dbt=1.5.9
17:04:29  Registered adapter: clickhouse=1.5.2
17:04:29  Unable to do partial parsing because config vars, config profile, or config target have changed
17:04:30  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 2
      config(


STDERR:
; 1094)
[2025-11-01T17:04:30.942+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T17:04:30.961+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
