[2025-11-01T17:30:21.105+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_payments manual__2025-11-01T17:30:19.194386+00:00 [queued]>
[2025-11-01T17:30:21.116+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_payments manual__2025-11-01T17:30:19.194386+00:00 [queued]>
[2025-11-01T17:30:21.117+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T17:30:21.132+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_payments> on 2025-11-01 17:30:19.194386+00:00
[2025-11-01T17:30:21.139+0000] {standard_task_runner.py:60} INFO - Started process 2715 to run task
[2025-11-01T17:30:21.145+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_payments', 'manual__2025-11-01T17:30:19.194386+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp2rt1qpn4']
[2025-11-01T17:30:21.148+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask dbt_run_payments
[2025-11-01T17:30:21.236+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_payments manual__2025-11-01T17:30:19.194386+00:00 [running]> on host 69cecc54c654
[2025-11-01T17:30:21.349+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_payments' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T17:30:19.194386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T17:30:19.194386+00:00'
[2025-11-01T17:30:26.501+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 180, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_payments", ds=ds, full_refresh=False, pass_ds_lagged=True),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (2).
STDOUT:
17:30:24  Running with dbt=1.5.9
17:30:24  Registered adapter: clickhouse=1.5.2
17:30:24  Unable to do partial parsing because config vars, config profile, or config target have changed
17:30:25  Encountered an error:
Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
  invalid syntax for function call expression
    line 4
      {{ config(


STDERR:

[2025-11-01T17:30:26.516+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_payments, execution_date=20251101T173019, start_date=20251101T173021, end_date=20251101T173026
[2025-11-01T17:30:26.529+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task dbt_run_payments (dbt failed (2).
STDOUT:
17:30:24  Running with dbt=1.5.9
17:30:24  Registered adapter: clickhouse=1.5.2
17:30:24  Unable to do partial parsing because config vars, config profile, or config target have changed
17:30:25  Encountered an error:
Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
  invalid syntax for function call expression
    line 4
      {{ config(


STDERR:
; 2715)
[2025-11-01T17:30:26.555+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T17:30:26.575+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
