[2025-10-31T22:58:44.882+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T22:58:39.086063+00:00 [queued]>
[2025-10-31T22:58:44.896+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T22:58:39.086063+00:00 [queued]>
[2025-10-31T22:58:44.897+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T22:58:44.915+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_incrementals> on 2025-10-31 22:58:39.086063+00:00
[2025-10-31T22:58:44.921+0000] {standard_task_runner.py:60} INFO - Started process 384 to run task
[2025-10-31T22:58:44.927+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_incrementals', 'manual__2025-10-31T22:58:39.086063+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpiceqm2cz']
[2025-10-31T22:58:44.931+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask silver_dbt.dbt_run_incrementals
[2025-10-31T22:58:45.028+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T22:58:39.086063+00:00 [running]> on host ad620feb6bee
[2025-10-31T22:58:45.159+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T22:58:39.086063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T22:58:39.086063+00:00'
[2025-10-31T22:58:45.166+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T22:58:45.168+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i dbt bash -lc \'\nset -e\ncd /dbt\nDBT_VARS=$(python - <<"PY"\nfrom datetime import datetime, timedelta\nimport json\nds = "2025-10-31"\nlag_days = 0\nlagged = (datetime.strptime(ds, "%Y-%m-%d") - timedelta(days=lag_days)).strftime("%Y-%m-%d")\nprint(json.dumps({"ds_lagged": lagged}))\nPY\n)\necho "dbt vars => ${DBT_VARS}"\ndbt --no-use-colors run --profiles-dir /dbt --select silver_payments silver_link_transactions --vars "${DBT_VARS}"\n\'']
[2025-10-31T22:58:45.183+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T22:58:45.359+0000] {subprocess.py:93} INFO - dbt vars => {"ds_lagged": "2025-10-31"}
[2025-10-31T22:58:47.841+0000] {subprocess.py:93} INFO - 22:58:47  Running with dbt=1.10.13
[2025-10-31T22:58:48.240+0000] {subprocess.py:93} INFO - 22:58:48  Registered adapter: clickhouse=1.9.5
[2025-10-31T22:58:48.587+0000] {subprocess.py:93} INFO - 22:58:48  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-10-31T22:58:50.571+0000] {subprocess.py:93} INFO - 22:58:50  Found 3 models, 3 sources, 491 macros
[2025-10-31T22:58:50.577+0000] {subprocess.py:93} INFO - 22:58:50
[2025-10-31T22:58:50.579+0000] {subprocess.py:93} INFO - 22:58:50  Concurrency: 4 threads (target='dev')
[2025-10-31T22:58:50.581+0000] {subprocess.py:93} INFO - 22:58:50
[2025-10-31T22:58:50.964+0000] {subprocess.py:93} INFO - 22:58:50  1 of 2 START sql incremental model `silver`.`silver_link_transactions` ......... [RUN]
[2025-10-31T22:58:50.966+0000] {subprocess.py:93} INFO - 22:58:50  2 of 2 START sql incremental model `silver`.`silver_payments` .................. [RUN]
[2025-10-31T22:58:51.143+0000] {subprocess.py:93} INFO - 22:58:51  1 of 2 ERROR creating sql incremental model `silver`.`silver_link_transactions`  [ERROR in 0.17s]
[2025-10-31T22:58:51.145+0000] {subprocess.py:93} INFO - 22:58:51  2 of 2 ERROR creating sql incremental model `silver`.`silver_payments` ......... [ERROR in 0.17s]
[2025-10-31T22:58:51.166+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.167+0000] {subprocess.py:93} INFO - 22:58:51  Finished running 2 incremental models in 0 hours 0 minutes and 0.58 seconds (0.58s).
[2025-10-31T22:58:51.261+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.262+0000] {subprocess.py:93} INFO - 22:58:51  Completed with 2 errors, 0 partial successes, and 0 warnings:
[2025-10-31T22:58:51.263+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.265+0000] {subprocess.py:93} INFO - 22:58:51  Failure in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T22:58:51.267+0000] {subprocess.py:93} INFO - 22:58:51    Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T22:58:51.268+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T22:58:51.268+0000] {subprocess.py:93} INFO - 
[2025-10-31T22:58:51.269+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T22:58:51.269+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T22:58:51.270+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T22:58:51.270+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T22:58:51.271+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-10-31T22:58:51.271+0000] {subprocess.py:93} INFO -   > called by model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T22:58:51.272+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.272+0000] {subprocess.py:93} INFO - 22:58:51    compiled code at target/compiled/ck_project/models/silver/silver_link_transactions.sql
[2025-10-31T22:58:51.273+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.274+0000] {subprocess.py:93} INFO - 22:58:51  Failure in model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T22:58:51.275+0000] {subprocess.py:93} INFO - 22:58:51    Compilation Error in model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T22:58:51.275+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T22:58:51.276+0000] {subprocess.py:93} INFO - 
[2025-10-31T22:58:51.277+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T22:58:51.277+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T22:58:51.278+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T22:58:51.278+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T22:58:51.279+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-10-31T22:58:51.279+0000] {subprocess.py:93} INFO -   > called by model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T22:58:51.280+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.282+0000] {subprocess.py:93} INFO - 22:58:51    compiled code at target/compiled/ck_project/models/silver/silver_payments.sql
[2025-10-31T22:58:51.283+0000] {subprocess.py:93} INFO - 22:58:51
[2025-10-31T22:58:51.283+0000] {subprocess.py:93} INFO - 22:58:51  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 NO-OP=0 TOTAL=2
[2025-10-31T22:58:52.500+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T22:58:52.524+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T22:58:52.531+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_incrementals, execution_date=20251031T225839, start_date=20251031T225844, end_date=20251031T225852
[2025-10-31T22:58:52.549+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task silver_dbt.dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 1.; 384)
[2025-10-31T22:58:52.598+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T22:58:52.619+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
