[2025-10-31T23:03:53.288+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T22:58:39.086063+00:00 [queued]>
[2025-10-31T23:03:53.360+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T22:58:39.086063+00:00 [queued]>
[2025-10-31T23:03:53.387+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T23:03:53.444+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_incrementals> on 2025-10-31 22:58:39.086063+00:00
[2025-10-31T23:03:53.477+0000] {standard_task_runner.py:60} INFO - Started process 781 to run task
[2025-10-31T23:03:53.492+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_incrementals', 'manual__2025-10-31T22:58:39.086063+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmp271jnrj0']
[2025-10-31T23:03:53.498+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask silver_dbt.dbt_run_incrementals
[2025-10-31T23:03:53.629+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T22:58:39.086063+00:00 [running]> on host ad620feb6bee
[2025-10-31T23:03:53.777+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T22:58:39.086063+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T22:58:39.086063+00:00'
[2025-10-31T23:03:53.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:03:53.787+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i dbt bash -lc \'\nset -e\ncd /dbt\nDBT_VARS=$(python - <<"PY"\nfrom datetime import datetime, timedelta\nimport json\nds = "2025-10-31"\nlag_days = 0\nlagged = (datetime.strptime(ds, "%Y-%m-%d") - timedelta(days=lag_days)).strftime("%Y-%m-%d")\nprint(json.dumps({"ds_lagged": lagged}))\nPY\n)\necho "dbt vars => ${DBT_VARS}"\ndbt --no-use-colors run --profiles-dir /dbt --select silver_payments silver_link_transactions --vars "${DBT_VARS}"\n\'']
[2025-10-31T23:03:53.803+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T23:03:53.969+0000] {subprocess.py:93} INFO - dbt vars => {"ds_lagged": "2025-10-31"}
[2025-10-31T23:03:56.204+0000] {subprocess.py:93} INFO - 23:03:56  Running with dbt=1.10.13
[2025-10-31T23:03:56.560+0000] {subprocess.py:93} INFO - 23:03:56  Registered adapter: clickhouse=1.9.5
[2025-10-31T23:03:56.783+0000] {subprocess.py:93} INFO - 23:03:56  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-10-31T23:03:59.017+0000] {subprocess.py:93} INFO - 23:03:59  Found 3 models, 3 sources, 491 macros
[2025-10-31T23:03:59.022+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.026+0000] {subprocess.py:93} INFO - 23:03:59  Concurrency: 4 threads (target='dev')
[2025-10-31T23:03:59.030+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.324+0000] {subprocess.py:93} INFO - 23:03:59  1 of 2 START sql incremental model `silver`.`silver_link_transactions` ......... [RUN]
[2025-10-31T23:03:59.326+0000] {subprocess.py:93} INFO - 23:03:59  2 of 2 START sql incremental model `silver`.`silver_payments` .................. [RUN]
[2025-10-31T23:03:59.465+0000] {subprocess.py:93} INFO - 23:03:59  1 of 2 ERROR creating sql incremental model `silver`.`silver_link_transactions`  [ERROR in 0.13s]
[2025-10-31T23:03:59.466+0000] {subprocess.py:93} INFO - 23:03:59  2 of 2 ERROR creating sql incremental model `silver`.`silver_payments` ......... [ERROR in 0.13s]
[2025-10-31T23:03:59.478+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.480+0000] {subprocess.py:93} INFO - 23:03:59  Finished running 2 incremental models in 0 hours 0 minutes and 0.45 seconds (0.45s).
[2025-10-31T23:03:59.530+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.532+0000] {subprocess.py:93} INFO - 23:03:59  Completed with 2 errors, 0 partial successes, and 0 warnings:
[2025-10-31T23:03:59.534+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.535+0000] {subprocess.py:93} INFO - 23:03:59  Failure in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T23:03:59.536+0000] {subprocess.py:93} INFO - 23:03:59    Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T23:03:59.537+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T23:03:59.537+0000] {subprocess.py:93} INFO - 
[2025-10-31T23:03:59.538+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T23:03:59.538+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:03:59.538+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:03:59.539+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T23:03:59.539+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-10-31T23:03:59.540+0000] {subprocess.py:93} INFO -   > called by model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-10-31T23:03:59.540+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.540+0000] {subprocess.py:93} INFO - 23:03:59    compiled code at target/compiled/ck_project/models/silver/silver_link_transactions.sql
[2025-10-31T23:03:59.541+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.541+0000] {subprocess.py:93} INFO - 23:03:59  Failure in model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T23:03:59.542+0000] {subprocess.py:93} INFO - 23:03:59    Compilation Error in model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T23:03:59.543+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T23:03:59.544+0000] {subprocess.py:93} INFO - 
[2025-10-31T23:03:59.544+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T23:03:59.545+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:03:59.545+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:03:59.546+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T23:03:59.546+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-10-31T23:03:59.547+0000] {subprocess.py:93} INFO -   > called by model silver_payments (models/silver/silver_payments.sql)
[2025-10-31T23:03:59.547+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.547+0000] {subprocess.py:93} INFO - 23:03:59    compiled code at target/compiled/ck_project/models/silver/silver_payments.sql
[2025-10-31T23:03:59.548+0000] {subprocess.py:93} INFO - 23:03:59
[2025-10-31T23:03:59.548+0000] {subprocess.py:93} INFO - 23:03:59  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 NO-OP=0 TOTAL=2
[2025-10-31T23:04:00.450+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:04:00.464+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:04:00.469+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_incrementals, execution_date=20251031T225839, start_date=20251031T230353, end_date=20251031T230400
[2025-10-31T23:04:00.485+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task silver_dbt.dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 1.; 781)
[2025-10-31T23:04:00.531+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T23:04:00.550+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
