[2025-11-01T11:41:28.591+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_incrementals manual__2025-11-01T11:41:21.867125+00:00 [queued]>
[2025-11-01T11:41:28.609+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_incrementals manual__2025-11-01T11:41:21.867125+00:00 [queued]>
[2025-11-01T11:41:28.610+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T11:41:28.641+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run_incrementals> on 2025-11-01 11:41:21.867125+00:00
[2025-11-01T11:41:28.653+0000] {standard_task_runner.py:60} INFO - Started process 680 to run task
[2025-11-01T11:41:28.665+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_incrementals', 'manual__2025-11-01T11:41:21.867125+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpi6m1nx8k']
[2025-11-01T11:41:28.671+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask dbt_run_incrementals
[2025-11-01T11:41:28.800+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_incrementals manual__2025-11-01T11:41:21.867125+00:00 [running]> on host 6ac9b46937d1
[2025-11-01T11:41:29.058+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T11:41:21.867125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T11:41:21.867125+00:00'
[2025-11-01T11:41:29.060+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T11:41:29.066+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ndocker exec -i dbt bash -lc \'\nset -e\ncd /dbt\n\n# Compute lagged date from Airflow-rendered 2025-11-01 without heredocs\nDBT_LAGGED=$(python -c "from datetime import datetime, timedelta; \\\nimport sys; print((datetime.strptime(\\"2025-11-01\\", \\"%Y-%m-%d\\") - timedelta(days=29)).strftime(\\"%Y-%m-%d\\"))")\n\nDBT_VARS="{\\"ds_lagged\\":\\"${DBT_LAGGED}\\"}"\necho "dbt vars => ${DBT_VARS}"\n\ndbt --no-use-colors run \\\n    --profiles-dir /dbt \\\n    --select silver_payments silver_link_transactions \\\n    --vars "${DBT_VARS}"\n\'']
[2025-11-01T11:41:29.094+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T11:41:29.357+0000] {subprocess.py:93} INFO - dbt vars => {"ds_lagged":"2025-10-03"}
[2025-11-01T11:41:32.761+0000] {subprocess.py:93} INFO - 11:41:32  Running with dbt=1.10.13
[2025-11-01T11:41:33.320+0000] {subprocess.py:93} INFO - 11:41:33  Registered adapter: clickhouse=1.9.5
[2025-11-01T11:41:33.729+0000] {subprocess.py:93} INFO - 11:41:33  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-11-01T11:41:36.774+0000] {subprocess.py:93} INFO - 11:41:36  Found 3 models, 3 sources, 491 macros
[2025-11-01T11:41:36.780+0000] {subprocess.py:93} INFO - 11:41:36
[2025-11-01T11:41:36.782+0000] {subprocess.py:93} INFO - 11:41:36  Concurrency: 4 threads (target='dev')
[2025-11-01T11:41:36.784+0000] {subprocess.py:93} INFO - 11:41:36
[2025-11-01T11:41:37.131+0000] {subprocess.py:93} INFO - 11:41:37  1 of 2 START sql incremental model `silver`.`silver_link_transactions` ......... [RUN]
[2025-11-01T11:41:37.133+0000] {subprocess.py:93} INFO - 11:41:37  2 of 2 START sql incremental model `silver`.`silver_payments` .................. [RUN]
[2025-11-01T11:41:37.335+0000] {subprocess.py:93} INFO - 11:41:37  2 of 2 ERROR creating sql incremental model `silver`.`silver_payments` ......... [ERROR in 0.19s]
[2025-11-01T11:41:37.337+0000] {subprocess.py:93} INFO - 11:41:37  1 of 2 ERROR creating sql incremental model `silver`.`silver_link_transactions`  [ERROR in 0.20s]
[2025-11-01T11:41:37.355+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.357+0000] {subprocess.py:93} INFO - 11:41:37  Finished running 2 incremental models in 0 hours 0 minutes and 0.57 seconds (0.57s).
[2025-11-01T11:41:37.483+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.490+0000] {subprocess.py:93} INFO - 11:41:37  Completed with 2 errors, 0 partial successes, and 0 warnings:
[2025-11-01T11:41:37.502+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.512+0000] {subprocess.py:93} INFO - 11:41:37  Failure in model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:41:37.513+0000] {subprocess.py:93} INFO - 11:41:37    Compilation Error in model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:41:37.516+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:41:37.517+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:41:37.521+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:41:37.522+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.523+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.525+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:41:37.529+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-11-01T11:41:37.532+0000] {subprocess.py:93} INFO -   > called by model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:41:37.533+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.537+0000] {subprocess.py:93} INFO - 11:41:37    compiled code at target/compiled/ck_project/models/silver/silver_payments.sql
[2025-11-01T11:41:37.539+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.540+0000] {subprocess.py:93} INFO - 11:41:37  Failure in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:41:37.541+0000] {subprocess.py:93} INFO - 11:41:37    Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:41:37.542+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:41:37.544+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:41:37.545+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:41:37.546+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.546+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.549+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:41:37.550+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-11-01T11:41:37.551+0000] {subprocess.py:93} INFO -   > called by model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:41:37.551+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.552+0000] {subprocess.py:93} INFO - 11:41:37    compiled code at target/compiled/ck_project/models/silver/silver_link_transactions.sql
[2025-11-01T11:41:37.553+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.554+0000] {subprocess.py:93} INFO - 11:41:37  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 NO-OP=0 TOTAL=2
[2025-11-01T11:41:38.660+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-11-01T11:41:38.679+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-11-01T11:41:38.685+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_incrementals, execution_date=20251101T114121, start_date=20251101T114128, end_date=20251101T114138
[2025-11-01T11:41:38.705+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 1.; 680)
[2025-11-01T11:41:38.743+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T11:41:38.768+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
