[2025-11-01T15:37:53.340+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T15:32:46.018721+00:00 [queued]>
[2025-11-01T15:37:53.360+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T15:32:46.018721+00:00 [queued]>
[2025-11-01T15:37:53.361+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-11-01T15:37:53.386+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_merchants> on 2025-11-01 15:32:46.018721+00:00
[2025-11-01T15:37:53.395+0000] {standard_task_runner.py:60} INFO - Started process 2838 to run task
[2025-11-01T15:37:53.400+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_merchants', 'manual__2025-11-01T15:32:46.018721+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp2i5mx77t']
[2025-11-01T15:37:53.404+0000] {standard_task_runner.py:88} INFO - Job 66: Subtask dbt_run_merchants
[2025-11-01T15:37:53.504+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T15:32:46.018721+00:00 [running]> on host 7f2b5a16b237
[2025-11-01T15:37:53.595+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T15:32:46.018721+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T15:32:46.018721+00:00'
[2025-11-01T15:37:59.598+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 184, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_merchants", ds=ds, full_refresh=True, pass_ds_lagged=False),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (1).
STDOUT:
15:37:56  Running with dbt=1.5.9
15:37:56  Registered adapter: clickhouse=1.5.2
15:37:56  Unable to do partial parsing because config vars, config profile, or config target have changed
15:37:58  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
15:37:58  
15:37:58  Concurrency: 4 threads (target='dev')
15:37:58  
15:37:58  1 of 1 START sql incremental model silver.silver_merchants ..................... [RUN]
15:37:58  1 of 1 ERROR creating sql incremental model silver.silver_merchants ............ [ERROR in 0.03s]
15:37:58  
15:37:58  Finished running 1 incremental model in 0 hours 0 minutes and 0.42 seconds (0.42s).
15:37:58  
15:37:58  Completed with 1 error and 0 warnings:
15:37:58  
15:37:58  Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
15:37:58    Required var 'ds_lagged' not found in config:
15:37:58    Vars supplied to silver_merchants = {}
15:37:58  
15:37:58  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1


STDERR:

[2025-11-01T15:37:59.615+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=silver_transformation_pipeline, task_id=dbt_run_merchants, execution_date=20251101T153246, start_date=20251101T153753, end_date=20251101T153759
[2025-11-01T15:37:59.633+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 66 for task dbt_run_merchants (dbt failed (1).
STDOUT:
15:37:56  Running with dbt=1.5.9
15:37:56  Registered adapter: clickhouse=1.5.2
15:37:56  Unable to do partial parsing because config vars, config profile, or config target have changed
15:37:58  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
15:37:58  
15:37:58  Concurrency: 4 threads (target='dev')
15:37:58  
15:37:58  1 of 1 START sql incremental model silver.silver_merchants ..................... [RUN]
15:37:58  1 of 1 ERROR creating sql incremental model silver.silver_merchants ............ [ERROR in 0.03s]
15:37:58  
15:37:58  Finished running 1 incremental model in 0 hours 0 minutes and 0.42 seconds (0.42s).
15:37:58  
15:37:58  Completed with 1 error and 0 warnings:
15:37:58  
15:37:58  Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
15:37:58    Required var 'ds_lagged' not found in config:
15:37:58    Vars supplied to silver_merchants = {}
15:37:58  
15:37:58  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1


STDERR:
; 2838)
[2025-11-01T15:37:59.688+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T15:37:59.717+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
