[2025-11-01T19:39:15.240+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T19:39:13.458232+00:00 [queued]>
[2025-11-01T19:39:15.251+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T19:39:13.458232+00:00 [queued]>
[2025-11-01T19:39:15.251+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T19:39:15.266+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_linktx> on 2025-11-01 19:39:13.458232+00:00
[2025-11-01T19:39:15.274+0000] {standard_task_runner.py:60} INFO - Started process 11532 to run task
[2025-11-01T19:39:15.277+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_linktx', 'manual__2025-11-01T19:39:13.458232+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpux_d64rq']
[2025-11-01T19:39:15.280+0000] {standard_task_runner.py:88} INFO - Job 211: Subtask dbt_run_linktx
[2025-11-01T19:39:15.363+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T19:39:13.458232+00:00 [running]> on host 69cecc54c654
[2025-11-01T19:39:15.477+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_linktx' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T19:39:13.458232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T19:39:13.458232+00:00'
[2025-11-01T19:39:19.481+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (2).
STDOUT:
19:39:18  Running with dbt=1.5.9
19:39:18  Registered adapter: clickhouse=1.5.2
19:39:18  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 8
      {{ config(


STDERR:

[2025-11-01T19:39:19.512+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_linktx, execution_date=20251101T193913, start_date=20251101T193915, end_date=20251101T193919
[2025-11-01T19:39:19.533+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 211 for task dbt_run_linktx (dbt failed (2).
STDOUT:
19:39:18  Running with dbt=1.5.9
19:39:18  Registered adapter: clickhouse=1.5.2
19:39:18  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 8
      {{ config(


STDERR:
; 11532)
[2025-11-01T19:39:19.546+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T19:39:19.572+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
