[2025-10-31T18:54:28.689+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-10-31T18:49:13.651453+00:00 [queued]>
[2025-10-31T18:54:28.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-10-31T18:49:13.651453+00:00 [queued]>
[2025-10-31T18:54:28.701+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T18:54:28.716+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run_merchants> on 2025-10-31 18:49:13.651453+00:00
[2025-10-31T18:54:28.722+0000] {standard_task_runner.py:60} INFO - Started process 988 to run task
[2025-10-31T18:54:28.727+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_merchants', 'manual__2025-10-31T18:49:13.651453+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp0s0p75u5']
[2025-10-31T18:54:28.730+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask dbt_run_merchants
[2025-10-31T18:54:28.812+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-10-31T18:49:13.651453+00:00 [running]> on host 516a89ff7ea8
[2025-10-31T18:54:28.899+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T18:49:13.651453+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T18:49:13.651453+00:00'
[2025-10-31T18:54:28.901+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T18:54:28.903+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec -i dbt bash -lc 'cd /dbt && dbt --no-use-colors run --profiles-dir /dbt --select silver_merchants --full-refresh'"]
[2025-10-31T18:54:28.915+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T18:54:30.870+0000] {subprocess.py:93} INFO - 18:54:30  Running with dbt=1.10.13
[2025-10-31T18:54:31.171+0000] {subprocess.py:93} INFO - 18:54:31  Registered adapter: clickhouse=1.9.5
[2025-10-31T18:54:31.344+0000] {subprocess.py:93} INFO - 18:54:31  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-10-31T18:54:32.554+0000] {subprocess.py:93} INFO - 18:54:32  Found 3 models, 3 sources, 488 macros
[2025-10-31T18:54:32.558+0000] {subprocess.py:93} INFO - 18:54:32
[2025-10-31T18:54:32.559+0000] {subprocess.py:93} INFO - 18:54:32  Concurrency: 4 threads (target='dev')
[2025-10-31T18:54:32.561+0000] {subprocess.py:93} INFO - 18:54:32
[2025-10-31T18:54:32.780+0000] {subprocess.py:93} INFO - 18:54:32  1 of 1 START sql table model `silver`.`silver_merchants` ....................... [RUN]
[2025-10-31T18:54:32.860+0000] {subprocess.py:93} INFO - 18:54:32  1 of 1 ERROR creating sql table model `silver`.`silver_merchants` .............. [ERROR in 0.07s]
[2025-10-31T18:54:32.870+0000] {subprocess.py:93} INFO - 18:54:32
[2025-10-31T18:54:32.872+0000] {subprocess.py:93} INFO - 18:54:32  Finished running 1 table model in 0 hours 0 minutes and 0.31 seconds (0.31s).
[2025-10-31T18:54:33.013+0000] {subprocess.py:93} INFO - 18:54:33
[2025-10-31T18:54:33.014+0000] {subprocess.py:93} INFO - 18:54:33  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-10-31T18:54:33.015+0000] {subprocess.py:93} INFO - 18:54:33
[2025-10-31T18:54:33.016+0000] {subprocess.py:93} INFO - 18:54:33  Failure in model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T18:54:33.017+0000] {subprocess.py:93} INFO - 18:54:33    Database Error in model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T18:54:33.017+0000] {subprocess.py:93} INFO -   Code: 62.
[2025-10-31T18:54:33.018+0000] {subprocess.py:93} INFO -   DB::Exception: Syntax error: failed at position 1187 (end of query) (line 42, col 30): ;
[2025-10-31T18:54:33.018+0000] {subprocess.py:93} INFO -             )
[2025-10-31T18:54:33.019+0000] {subprocess.py:93} INFO - 
[2025-10-31T18:54:33.020+0000] {subprocess.py:93} INFO -           . Expected one of: OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, GROUP BY, WITH, HAVING, WINDOW, QUALIFY, ORDER BY, LIMIT, OFFSET, FETCH, SETTINGS, UNION, EXCEPT, INTERSECT. Stack trace:
[2025-10-31T18:54:33.020+0000] {subprocess.py:93} INFO - 
[2025-10-31T18:54:33.021+0000] {subprocess.py:93} INFO -   0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
[2025-10-31T18:54:33.021+0000] {subprocess.py:93} INFO -   1. DB::Exception::Exception(String const&, int, String, bool) @ 0x0000000012423c8e
[2025-10-31T18:54:33.022+0000] {subprocess.py:93} INFO -   2. DB::Exception::createDeprecated(String const&, int, bool) @ 0x0000000013a54f9f
[2025-10-31T18:54:33.022+0000] {subprocess.py:93} INFO -   3. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long, unsigned long) @ 0x000000001aace132
[2025-10-31T18:54:33.023+0000] {subprocess.py:93} INFO -   4. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018779652
[2025-10-31T18:54:33.023+0000] {subprocess.py:93} INFO -   5. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000187786cb
[2025-10-31T18:54:33.024+0000] {subprocess.py:93} INFO -   6. DB::TCPHandler::runImpl() @ 0x0000000019e2d3db
[2025-10-31T18:54:33.024+0000] {subprocess.py:93} INFO -   7. DB::TCPHandler::run() @ 0x0000000019e4f119
[2025-10-31T18:54:33.024+0000] {subprocess.py:93} INFO -   8. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
[2025-10-31T18:54:33.025+0000] {subprocess.py:93} INFO -   9. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
[2025-10-31T18:54:33.025+0000] {subprocess.py:93} INFO -   10. Poco::PooledThread::run() @ 0x000000001ef15b87
[2025-10-31T18:54:33.026+0000] {subprocess.py:93} INFO -   11. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
[2025-10-31T18:54:33.026+0000] {subprocess.py:93} INFO -   12. ? @ 0x0000000000094ac3
[2025-10-31T18:54:33.027+0000] {subprocess.py:93} INFO -   13. ? @ 0x0000000000125a74
[2025-10-31T18:54:33.027+0000] {subprocess.py:93} INFO - 18:54:33
[2025-10-31T18:54:33.027+0000] {subprocess.py:93} INFO - 18:54:33    compiled code at target/compiled/ck_project/models/silver/silver_merchants.sql
[2025-10-31T18:54:33.028+0000] {subprocess.py:93} INFO - 18:54:33
[2025-10-31T18:54:33.028+0000] {subprocess.py:93} INFO - 18:54:33  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
[2025-10-31T18:54:33.852+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T18:54:33.865+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T18:54:33.868+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=silver_transformation_pipeline, task_id=dbt_run_merchants, execution_date=20251031T184913, start_date=20251031T185428, end_date=20251031T185433
[2025-10-31T18:54:33.884+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task dbt_run_merchants (Bash command failed. The command returned a non-zero exit code 1.; 988)
[2025-10-31T18:54:33.930+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T18:54:33.948+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
