[2025-10-31T20:08:28.134+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T20:08:19.566196+00:00 [queued]>
[2025-10-31T20:08:28.145+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T20:08:19.566196+00:00 [queued]>
[2025-10-31T20:08:28.146+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T20:08:28.164+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_merchants> on 2025-10-31 20:08:19.566196+00:00
[2025-10-31T20:08:28.172+0000] {standard_task_runner.py:60} INFO - Started process 695 to run task
[2025-10-31T20:08:28.176+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_merchants', 'manual__2025-10-31T20:08:19.566196+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpg4ulf_tn']
[2025-10-31T20:08:28.178+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask silver_dbt.dbt_run_merchants
[2025-10-31T20:08:28.253+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T20:08:19.566196+00:00 [running]> on host c2d20b09a38d
[2025-10-31T20:08:28.352+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T20:08:19.566196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T20:08:19.566196+00:00'
[2025-10-31T20:08:28.354+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T20:08:28.355+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec -i dbt bash -lc 'cd /dbt && dbt --no-use-colors run --profiles-dir /dbt --select silver_merchants --full-refresh'"]
[2025-10-31T20:08:28.366+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T20:08:30.054+0000] {subprocess.py:93} INFO - 20:08:30  Running with dbt=1.10.13
[2025-10-31T20:08:30.306+0000] {subprocess.py:93} INFO - 20:08:30  Registered adapter: clickhouse=1.9.5
[2025-10-31T20:08:30.486+0000] {subprocess.py:93} INFO - 20:08:30  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-10-31T20:08:32.002+0000] {subprocess.py:93} INFO - 20:08:32  Found 3 models, 3 sources, 488 macros
[2025-10-31T20:08:32.006+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.008+0000] {subprocess.py:93} INFO - 20:08:32  Concurrency: 4 threads (target='dev')
[2025-10-31T20:08:32.009+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.273+0000] {subprocess.py:93} INFO - 20:08:32  1 of 1 START sql table model `silver`.`silver_merchants` ....................... [RUN]
[2025-10-31T20:08:32.373+0000] {subprocess.py:93} INFO - 20:08:32  1 of 1 ERROR creating sql table model `silver`.`silver_merchants` .............. [ERROR in 0.10s]
[2025-10-31T20:08:32.386+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.387+0000] {subprocess.py:93} INFO - 20:08:32  Finished running 1 table model in 0 hours 0 minutes and 0.37 seconds (0.37s).
[2025-10-31T20:08:32.545+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.546+0000] {subprocess.py:93} INFO - 20:08:32  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-10-31T20:08:32.547+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.549+0000] {subprocess.py:93} INFO - 20:08:32  Failure in model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T20:08:32.551+0000] {subprocess.py:93} INFO - 20:08:32    Database Error in model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T20:08:32.554+0000] {subprocess.py:93} INFO -   Code: 62.
[2025-10-31T20:08:32.556+0000] {subprocess.py:93} INFO -   DB::Exception: Syntax error: failed at position 1187 (end of query) (line 42, col 30): ;
[2025-10-31T20:08:32.557+0000] {subprocess.py:93} INFO -             )
[2025-10-31T20:08:32.559+0000] {subprocess.py:93} INFO - 
[2025-10-31T20:08:32.561+0000] {subprocess.py:93} INFO -           . Expected one of: OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, GROUP BY, WITH, HAVING, WINDOW, QUALIFY, ORDER BY, LIMIT, OFFSET, FETCH, SETTINGS, UNION, EXCEPT, INTERSECT. Stack trace:
[2025-10-31T20:08:32.561+0000] {subprocess.py:93} INFO - 
[2025-10-31T20:08:32.562+0000] {subprocess.py:93} INFO -   0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
[2025-10-31T20:08:32.563+0000] {subprocess.py:93} INFO -   1. DB::Exception::Exception(String const&, int, String, bool) @ 0x0000000012423c8e
[2025-10-31T20:08:32.564+0000] {subprocess.py:93} INFO -   2. DB::Exception::createDeprecated(String const&, int, bool) @ 0x0000000013a54f9f
[2025-10-31T20:08:32.564+0000] {subprocess.py:93} INFO -   3. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long, unsigned long) @ 0x000000001aace132
[2025-10-31T20:08:32.564+0000] {subprocess.py:93} INFO -   4. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018779652
[2025-10-31T20:08:32.565+0000] {subprocess.py:93} INFO -   5. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000187786cb
[2025-10-31T20:08:32.565+0000] {subprocess.py:93} INFO -   6. DB::TCPHandler::runImpl() @ 0x0000000019e2d3db
[2025-10-31T20:08:32.566+0000] {subprocess.py:93} INFO -   7. DB::TCPHandler::run() @ 0x0000000019e4f119
[2025-10-31T20:08:32.566+0000] {subprocess.py:93} INFO -   8. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
[2025-10-31T20:08:32.567+0000] {subprocess.py:93} INFO -   9. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
[2025-10-31T20:08:32.567+0000] {subprocess.py:93} INFO -   10. Poco::PooledThread::run() @ 0x000000001ef15b87
[2025-10-31T20:08:32.568+0000] {subprocess.py:93} INFO -   11. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
[2025-10-31T20:08:32.568+0000] {subprocess.py:93} INFO -   12. ? @ 0x0000000000094ac3
[2025-10-31T20:08:32.569+0000] {subprocess.py:93} INFO -   13. ? @ 0x0000000000125a74
[2025-10-31T20:08:32.569+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.570+0000] {subprocess.py:93} INFO - 20:08:32    compiled code at target/compiled/ck_project/models/silver/silver_merchants.sql
[2025-10-31T20:08:32.570+0000] {subprocess.py:93} INFO - 20:08:32
[2025-10-31T20:08:32.571+0000] {subprocess.py:93} INFO - 20:08:32  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
[2025-10-31T20:08:33.385+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T20:08:33.402+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T20:08:33.406+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_merchants, execution_date=20251031T200819, start_date=20251031T200828, end_date=20251031T200833
[2025-10-31T20:08:33.421+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task silver_dbt.dbt_run_merchants (Bash command failed. The command returned a non-zero exit code 1.; 695)
[2025-10-31T20:08:33.460+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T20:08:33.482+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
