[2025-11-01T15:30:06.104+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T15:30:03.658229+00:00 [queued]>
[2025-11-01T15:30:06.120+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T15:30:03.658229+00:00 [queued]>
[2025-11-01T15:30:06.121+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T15:30:06.140+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_merchants> on 2025-11-01 15:30:03.658229+00:00
[2025-11-01T15:30:06.149+0000] {standard_task_runner.py:60} INFO - Started process 2228 to run task
[2025-11-01T15:30:06.154+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_merchants', 'manual__2025-11-01T15:30:03.658229+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmptr1kskn_']
[2025-11-01T15:30:06.159+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask dbt_run_merchants
[2025-11-01T15:30:06.281+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T15:30:03.658229+00:00 [running]> on host 7f2b5a16b237
[2025-11-01T15:30:06.430+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T15:30:03.658229+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T15:30:03.658229+00:00'
[2025-11-01T15:30:12.023+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 190, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_merchants", ds=ds, full_refresh=True, pass_ds_lagged=False),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (1).
STDOUT:
15:30:09  Running with dbt=1.5.9
15:30:09  Registered adapter: clickhouse=1.5.2
15:30:09  Unable to do partial parsing because config vars, config profile, or config target have changed
15:30:10  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
15:30:10  
15:30:11  Concurrency: 4 threads (target='dev')
15:30:11  
15:30:11  1 of 1 START sql incremental model silver.silver_merchants ..................... [RUN]
15:30:11  1 of 1 ERROR creating sql incremental model silver.silver_merchants ............ [ERROR in 0.02s]
15:30:11  
15:30:11  Finished running 1 incremental model in 0 hours 0 minutes and 0.33 seconds (0.33s).
15:30:11  
15:30:11  Completed with 1 error and 0 warnings:
15:30:11  
15:30:11  Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
15:30:11    Required var 'ds_lagged' not found in config:
15:30:11    Vars supplied to silver_merchants = {}
15:30:11  
15:30:11  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1


STDERR:

[2025-11-01T15:30:12.043+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_merchants, execution_date=20251101T153003, start_date=20251101T153006, end_date=20251101T153012
[2025-11-01T15:30:12.074+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task dbt_run_merchants (dbt failed (1).
STDOUT:
15:30:09  Running with dbt=1.5.9
15:30:09  Registered adapter: clickhouse=1.5.2
15:30:09  Unable to do partial parsing because config vars, config profile, or config target have changed
15:30:10  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
15:30:10  
15:30:11  Concurrency: 4 threads (target='dev')
15:30:11  
15:30:11  1 of 1 START sql incremental model silver.silver_merchants ..................... [RUN]
15:30:11  1 of 1 ERROR creating sql incremental model silver.silver_merchants ............ [ERROR in 0.02s]
15:30:11  
15:30:11  Finished running 1 incremental model in 0 hours 0 minutes and 0.33 seconds (0.33s).
15:30:11  
15:30:11  Completed with 1 error and 0 warnings:
15:30:11  
15:30:11  Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
15:30:11    Required var 'ds_lagged' not found in config:
15:30:11    Vars supplied to silver_merchants = {}
15:30:11  
15:30:11  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1


STDERR:
; 2228)
[2025-11-01T15:30:12.126+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T15:30:12.155+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
