[2025-10-31T23:17:33.970+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T23:12:23.731239+00:00 [queued]>
[2025-10-31T23:17:33.981+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T23:12:23.731239+00:00 [queued]>
[2025-10-31T23:17:33.981+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T23:17:33.997+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_merchants> on 2025-10-31 23:12:23.731239+00:00
[2025-10-31T23:17:34.005+0000] {standard_task_runner.py:60} INFO - Started process 1871 to run task
[2025-10-31T23:17:34.009+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_merchants', 'manual__2025-10-31T23:12:23.731239+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpl2bnnm2f']
[2025-10-31T23:17:34.013+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask silver_dbt.dbt_run_merchants
[2025-10-31T23:17:34.095+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-10-31T23:12:23.731239+00:00 [running]> on host ad620feb6bee
[2025-10-31T23:17:34.188+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T23:12:23.731239+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T23:12:23.731239+00:00'
[2025-10-31T23:17:34.190+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T23:17:34.194+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec -i dbt bash -lc 'set -e; cd /dbt && dbt --no-use-colors run --profiles-dir /dbt --select silver_merchants --full-refresh'"]
[2025-10-31T23:17:34.207+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T23:17:36.064+0000] {subprocess.py:93} INFO - 23:17:36  Running with dbt=1.10.13
[2025-10-31T23:17:36.366+0000] {subprocess.py:93} INFO - 23:17:36  Registered adapter: clickhouse=1.9.5
[2025-10-31T23:17:36.842+0000] {subprocess.py:93} INFO - 23:17:36  Found 3 models, 3 sources, 491 macros
[2025-10-31T23:17:36.847+0000] {subprocess.py:93} INFO - 23:17:36
[2025-10-31T23:17:36.849+0000] {subprocess.py:93} INFO - 23:17:36  Concurrency: 4 threads (target='dev')
[2025-10-31T23:17:36.851+0000] {subprocess.py:93} INFO - 23:17:36
[2025-10-31T23:17:37.172+0000] {subprocess.py:93} INFO - 23:17:37  1 of 1 START sql table model `silver`.`silver_merchants` ....................... [RUN]
[2025-10-31T23:17:37.307+0000] {subprocess.py:93} INFO - 23:17:37  1 of 1 ERROR creating sql table model `silver`.`silver_merchants` .............. [ERROR in 0.13s]
[2025-10-31T23:17:37.317+0000] {subprocess.py:93} INFO - 23:17:37
[2025-10-31T23:17:37.318+0000] {subprocess.py:93} INFO - 23:17:37  Finished running 1 table model in 0 hours 0 minutes and 0.46 seconds (0.46s).
[2025-10-31T23:17:37.387+0000] {subprocess.py:93} INFO - 23:17:37
[2025-10-31T23:17:37.389+0000] {subprocess.py:93} INFO - 23:17:37  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-10-31T23:17:37.392+0000] {subprocess.py:93} INFO - 23:17:37
[2025-10-31T23:17:37.393+0000] {subprocess.py:93} INFO - 23:17:37  Failure in model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T23:17:37.395+0000] {subprocess.py:93} INFO - 23:17:37    Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T23:17:37.395+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-10-31T23:17:37.396+0000] {subprocess.py:93} INFO - 
[2025-10-31T23:17:37.396+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-10-31T23:17:37.397+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:17:37.398+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-10-31T23:17:37.398+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-10-31T23:17:37.399+0000] {subprocess.py:93} INFO -   > called by macro materialization_table_clickhouse (macros/materializations/table.sql)
[2025-10-31T23:17:37.400+0000] {subprocess.py:93} INFO -   > called by model silver_merchants (models/silver/silver_merchants.sql)
[2025-10-31T23:17:37.401+0000] {subprocess.py:93} INFO - 23:17:37
[2025-10-31T23:17:37.402+0000] {subprocess.py:93} INFO - 23:17:37    compiled code at target/compiled/ck_project/models/silver/silver_merchants.sql
[2025-10-31T23:17:37.404+0000] {subprocess.py:93} INFO - 23:17:37
[2025-10-31T23:17:37.405+0000] {subprocess.py:93} INFO - 23:17:37  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
[2025-10-31T23:17:38.356+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T23:17:38.375+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T23:17:38.379+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_merchants, execution_date=20251031T231223, start_date=20251031T231733, end_date=20251031T231738
[2025-10-31T23:17:38.394+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task silver_dbt.dbt_run_merchants (Bash command failed. The command returned a non-zero exit code 1.; 1871)
[2025-10-31T23:17:38.442+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T23:17:38.476+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
