[2025-11-01T18:57:08.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T18:51:58.758403+00:00 [queued]>
[2025-11-01T18:57:08.149+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T18:51:58.758403+00:00 [queued]>
[2025-11-01T18:57:08.150+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-11-01T18:57:08.170+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_linktx> on 2025-11-01 18:51:58.758403+00:00
[2025-11-01T18:57:08.179+0000] {standard_task_runner.py:60} INFO - Started process 8608 to run task
[2025-11-01T18:57:08.186+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_linktx', 'manual__2025-11-01T18:51:58.758403+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpdcy03qz6']
[2025-11-01T18:57:08.190+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask dbt_run_linktx
[2025-11-01T18:57:08.288+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T18:51:58.758403+00:00 [running]> on host 69cecc54c654
[2025-11-01T18:57:08.399+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_linktx' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T18:51:58.758403+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T18:51:58.758403+00:00'
[2025-11-01T18:57:13.113+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (2).
STDOUT:
18:57:10  Running with dbt=1.5.9
18:57:11  Registered adapter: clickhouse=1.5.2
18:57:11  Unable to do partial parsing because config vars, config profile, or config target have changed
18:57:12  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 7
      {{ config(


STDERR:

[2025-11-01T18:57:13.128+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=silver_transformation_pipeline, task_id=dbt_run_linktx, execution_date=20251101T185158, start_date=20251101T185708, end_date=20251101T185713
[2025-11-01T18:57:13.146+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 162 for task dbt_run_linktx (dbt failed (2).
STDOUT:
18:57:10  Running with dbt=1.5.9
18:57:11  Registered adapter: clickhouse=1.5.2
18:57:11  Unable to do partial parsing because config vars, config profile, or config target have changed
18:57:12  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 7
      {{ config(


STDERR:
; 8608)
[2025-11-01T18:57:13.182+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T18:57:13.200+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
