[2025-11-01T11:48:26.148+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-11-01T11:48:21.369842+00:00 [queued]>
[2025-11-01T11:48:26.162+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-11-01T11:48:21.369842+00:00 [queued]>
[2025-11-01T11:48:26.163+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T11:48:26.181+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_merchants> on 2025-11-01 11:48:21.369842+00:00
[2025-11-01T11:48:26.188+0000] {standard_task_runner.py:60} INFO - Started process 1384 to run task
[2025-11-01T11:48:26.193+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_merchants', 'manual__2025-11-01T11:48:21.369842+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpsq7ezbo6']
[2025-11-01T11:48:26.197+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask silver_dbt.dbt_run_merchants
[2025-11-01T11:48:26.280+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-11-01T11:48:21.369842+00:00 [running]> on host 6ac9b46937d1
[2025-11-01T11:48:26.386+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T11:48:21.369842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T11:48:21.369842+00:00'
[2025-11-01T11:48:26.393+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T11:48:26.395+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec -i dbt bash -lc 'cd /dbt && dbt --no-use-colors run --profiles-dir /dbt --select silver_merchants --full-refresh'"]
[2025-11-01T11:48:26.408+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T11:48:28.527+0000] {subprocess.py:93} INFO - 11:48:28  Running with dbt=1.10.13
[2025-11-01T11:48:29.340+0000] {subprocess.py:93} INFO - 11:48:29  Registered adapter: clickhouse=1.9.5
[2025-11-01T11:48:29.938+0000] {subprocess.py:93} INFO - 11:48:29  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-11-01T11:48:32.229+0000] {subprocess.py:93} INFO - 11:48:32  Found 3 models, 3 sources, 491 macros
[2025-11-01T11:48:32.239+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.242+0000] {subprocess.py:93} INFO - 11:48:32  Concurrency: 4 threads (target='dev')
[2025-11-01T11:48:32.244+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.552+0000] {subprocess.py:93} INFO - 11:48:32  1 of 1 START sql table model `silver`.`silver_merchants` ....................... [RUN]
[2025-11-01T11:48:32.644+0000] {subprocess.py:93} INFO - 11:48:32  1 of 1 ERROR creating sql table model `silver`.`silver_merchants` .............. [ERROR in 0.09s]
[2025-11-01T11:48:32.658+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.660+0000] {subprocess.py:93} INFO - 11:48:32  Finished running 1 table model in 0 hours 0 minutes and 0.41 seconds (0.41s).
[2025-11-01T11:48:32.853+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.856+0000] {subprocess.py:93} INFO - 11:48:32  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-11-01T11:48:32.857+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.858+0000] {subprocess.py:93} INFO - 11:48:32  Failure in model silver_merchants (models/silver/silver_merchants.sql)
[2025-11-01T11:48:32.861+0000] {subprocess.py:93} INFO - 11:48:32    Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
[2025-11-01T11:48:32.862+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:48:32.862+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:48:32.865+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:48:32.870+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:48:32.872+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:48:32.874+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:48:32.876+0000] {subprocess.py:93} INFO -   > called by macro materialization_table_clickhouse (macros/materializations/table.sql)
[2025-11-01T11:48:32.876+0000] {subprocess.py:93} INFO -   > called by model silver_merchants (models/silver/silver_merchants.sql)
[2025-11-01T11:48:32.877+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.878+0000] {subprocess.py:93} INFO - 11:48:32    compiled code at target/compiled/ck_project/models/silver/silver_merchants.sql
[2025-11-01T11:48:32.878+0000] {subprocess.py:93} INFO - 11:48:32
[2025-11-01T11:48:32.879+0000] {subprocess.py:93} INFO - 11:48:32  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
[2025-11-01T11:48:34.057+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-11-01T11:48:34.075+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-11-01T11:48:34.080+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_merchants, execution_date=20251101T114821, start_date=20251101T114826, end_date=20251101T114834
[2025-11-01T11:48:34.100+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task silver_dbt.dbt_run_merchants (Bash command failed. The command returned a non-zero exit code 1.; 1384)
[2025-11-01T11:48:34.118+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T11:48:34.140+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
