[2025-11-01T11:41:28.609+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_incrementals scheduled__2025-10-31T00:00:00+00:00 [queued]>
[2025-11-01T11:41:28.624+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_incrementals scheduled__2025-10-31T00:00:00+00:00 [queued]>
[2025-11-01T11:41:28.625+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T11:41:28.659+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run_incrementals> on 2025-10-31 00:00:00+00:00
[2025-11-01T11:41:28.674+0000] {standard_task_runner.py:60} INFO - Started process 683 to run task
[2025-11-01T11:41:28.683+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_incrementals', 'scheduled__2025-10-31T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmp70e7ayb6']
[2025-11-01T11:41:28.688+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask dbt_run_incrementals
[2025-11-01T11:41:28.825+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_incrementals scheduled__2025-10-31T00:00:00+00:00 [running]> on host 6ac9b46937d1
[2025-11-01T11:41:29.062+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T00:00:00+00:00'
[2025-11-01T11:41:29.066+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T11:41:29.070+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ndocker exec -i dbt bash -lc \'\nset -e\ncd /dbt\n\n# Compute lagged date from Airflow-rendered 2025-10-31 without heredocs\nDBT_LAGGED=$(python -c "from datetime import datetime, timedelta; \\\nimport sys; print((datetime.strptime(\\"2025-10-31\\", \\"%Y-%m-%d\\") - timedelta(days=29)).strftime(\\"%Y-%m-%d\\"))")\n\nDBT_VARS="{\\"ds_lagged\\":\\"${DBT_LAGGED}\\"}"\necho "dbt vars => ${DBT_VARS}"\n\ndbt --no-use-colors run \\\n    --profiles-dir /dbt \\\n    --select silver_payments silver_link_transactions \\\n    --vars "${DBT_VARS}"\n\'']
[2025-11-01T11:41:29.102+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T11:41:29.360+0000] {subprocess.py:93} INFO - dbt vars => {"ds_lagged":"2025-10-02"}
[2025-11-01T11:41:32.769+0000] {subprocess.py:93} INFO - 11:41:32  Running with dbt=1.10.13
[2025-11-01T11:41:33.327+0000] {subprocess.py:93} INFO - 11:41:33  Registered adapter: clickhouse=1.9.5
[2025-11-01T11:41:33.706+0000] {subprocess.py:93} INFO - 11:41:33  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-11-01T11:41:36.708+0000] {subprocess.py:93} INFO - 11:41:36  Found 3 models, 3 sources, 491 macros
[2025-11-01T11:41:36.713+0000] {subprocess.py:93} INFO - 11:41:36
[2025-11-01T11:41:36.714+0000] {subprocess.py:93} INFO - 11:41:36  Concurrency: 4 threads (target='dev')
[2025-11-01T11:41:36.716+0000] {subprocess.py:93} INFO - 11:41:36
[2025-11-01T11:41:37.053+0000] {subprocess.py:93} INFO - 11:41:37  1 of 2 START sql incremental model `silver`.`silver_link_transactions` ......... [RUN]
[2025-11-01T11:41:37.056+0000] {subprocess.py:93} INFO - 11:41:37  2 of 2 START sql incremental model `silver`.`silver_payments` .................. [RUN]
[2025-11-01T11:41:37.347+0000] {subprocess.py:93} INFO - 11:41:37  2 of 2 ERROR creating sql incremental model `silver`.`silver_payments` ......... [ERROR in 0.28s]
[2025-11-01T11:41:37.350+0000] {subprocess.py:93} INFO - 11:41:37  1 of 2 ERROR creating sql incremental model `silver`.`silver_link_transactions`  [ERROR in 0.29s]
[2025-11-01T11:41:37.371+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.373+0000] {subprocess.py:93} INFO - 11:41:37  Finished running 2 incremental models in 0 hours 0 minutes and 0.65 seconds (0.65s).
[2025-11-01T11:41:37.549+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.554+0000] {subprocess.py:93} INFO - 11:41:37  Completed with 2 errors, 0 partial successes, and 0 warnings:
[2025-11-01T11:41:37.557+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.560+0000] {subprocess.py:93} INFO - 11:41:37  Failure in model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:41:37.564+0000] {subprocess.py:93} INFO - 11:41:37    Compilation Error in model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:41:37.566+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:41:37.568+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:41:37.569+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:41:37.570+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.570+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.575+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:41:37.575+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-11-01T11:41:37.577+0000] {subprocess.py:93} INFO -   > called by model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:41:37.579+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.580+0000] {subprocess.py:93} INFO - 11:41:37    compiled code at target/compiled/ck_project/models/silver/silver_payments.sql
[2025-11-01T11:41:37.580+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.582+0000] {subprocess.py:93} INFO - 11:41:37  Failure in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:41:37.583+0000] {subprocess.py:93} INFO - 11:41:37    Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:41:37.584+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:41:37.585+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:41:37.588+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:41:37.589+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.589+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:37.590+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:41:37.591+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-11-01T11:41:37.592+0000] {subprocess.py:93} INFO -   > called by model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:41:37.593+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.594+0000] {subprocess.py:93} INFO - 11:41:37    compiled code at target/compiled/ck_project/models/silver/silver_link_transactions.sql
[2025-11-01T11:41:37.596+0000] {subprocess.py:93} INFO - 11:41:37
[2025-11-01T11:41:37.598+0000] {subprocess.py:93} INFO - 11:41:37  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 NO-OP=0 TOTAL=2
[2025-11-01T11:41:38.711+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-11-01T11:41:38.732+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-11-01T11:41:38.736+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_incrementals, execution_date=20251031T000000, start_date=20251101T114128, end_date=20251101T114138
[2025-11-01T11:41:38.757+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 1.; 683)
[2025-11-01T11:41:38.784+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T11:41:38.809+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
