[2025-10-31T19:08:44.702+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T19:03:36.371075+00:00 [queued]>
[2025-10-31T19:08:44.712+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T19:03:36.371075+00:00 [queued]>
[2025-10-31T19:08:44.713+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T19:08:44.727+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_incrementals> on 2025-10-31 19:03:36.371075+00:00
[2025-10-31T19:08:44.732+0000] {standard_task_runner.py:60} INFO - Started process 997 to run task
[2025-10-31T19:08:44.736+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_incrementals', 'manual__2025-10-31T19:03:36.371075+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmplmhxxw0y']
[2025-10-31T19:08:44.739+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask silver_dbt.dbt_run_incrementals
[2025-10-31T19:08:44.819+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_incrementals manual__2025-10-31T19:03:36.371075+00:00 [running]> on host fe1087a1e328
[2025-10-31T19:08:44.902+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T19:03:36.371075+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T19:03:36.371075+00:00'
[2025-10-31T19:08:44.904+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T19:08:44.905+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i dbt bash -lc \'set -e; cd /dbt; python - <<"PY"\nfrom datetime import datetime, timedelta\nimport json\nds = "2025-10-31"\nlag_days = 29\nlagged = (datetime.strptime(ds, "%Y-%m-%d") - timedelta(days=lag_days)).strftime("%Y-%m-%d")\nprint(json.dumps({"ds_lagged": lagged}))\nPY\n| tee /tmp/dbt_vars.json > /dev/null; echo "dbt vars => $(cat /tmp/dbt_vars.json)"; dbt --no-use-colors run --profiles-dir /dbt --select silver_payments silver_link_transactions --vars "$(cat /tmp/dbt_vars.json)"\'']
[2025-10-31T19:08:44.915+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T19:08:45.057+0000] {subprocess.py:93} INFO - {"ds_lagged": "2025-10-02"}
[2025-10-31T19:08:45.060+0000] {subprocess.py:93} INFO - bash: -c: line 9: syntax error near unexpected token `|'
[2025-10-31T19:08:45.066+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-10-31T19:08:45.081+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-10-31T19:08:45.084+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_incrementals, execution_date=20251031T190336, start_date=20251031T190844, end_date=20251031T190845
[2025-10-31T19:08:45.098+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task silver_dbt.dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 2.; 997)
[2025-10-31T19:08:45.111+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T19:08:45.129+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
