[2025-11-01T11:46:39.729+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_incrementals scheduled__2025-10-30T00:00:00+00:00 [queued]>
[2025-11-01T11:46:39.746+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_incrementals scheduled__2025-10-30T00:00:00+00:00 [queued]>
[2025-11-01T11:46:39.747+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-11-01T11:46:39.776+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run_incrementals> on 2025-10-30 00:00:00+00:00
[2025-11-01T11:46:39.787+0000] {standard_task_runner.py:60} INFO - Started process 1219 to run task
[2025-11-01T11:46:39.793+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_incrementals', 'scheduled__2025-10-30T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpyr5c7_if']
[2025-11-01T11:46:39.798+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask dbt_run_incrementals
[2025-11-01T11:46:39.963+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_incrementals scheduled__2025-10-30T00:00:00+00:00 [running]> on host 6ac9b46937d1
[2025-11-01T11:46:40.141+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_incrementals' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T00:00:00+00:00'
[2025-11-01T11:46:40.145+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T11:46:40.147+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ndocker exec -i dbt bash -lc \'\nset -e\ncd /dbt\n\n# Compute lagged date from Airflow-rendered 2025-10-30 without heredocs\nDBT_LAGGED=$(python -c "from datetime import datetime, timedelta; \\\nimport sys; print((datetime.strptime(\\"2025-10-30\\", \\"%Y-%m-%d\\") - timedelta(days=29)).strftime(\\"%Y-%m-%d\\"))")\n\nDBT_VARS="{\\"ds_lagged\\":\\"${DBT_LAGGED}\\"}"\necho "dbt vars => ${DBT_VARS}"\n\ndbt --no-use-colors run \\\n    --profiles-dir /dbt \\\n    --select silver_payments silver_link_transactions \\\n    --vars "${DBT_VARS}"\n\'']
[2025-11-01T11:46:40.173+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T11:46:40.422+0000] {subprocess.py:93} INFO - dbt vars => {"ds_lagged":"2025-10-01"}
[2025-11-01T11:46:43.420+0000] {subprocess.py:93} INFO - 11:46:43  Running with dbt=1.10.13
[2025-11-01T11:46:43.969+0000] {subprocess.py:93} INFO - 11:46:43  Registered adapter: clickhouse=1.9.5
[2025-11-01T11:46:44.373+0000] {subprocess.py:93} INFO - 11:46:44  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-11-01T11:46:46.936+0000] {subprocess.py:93} INFO - 11:46:46  Found 3 models, 3 sources, 491 macros
[2025-11-01T11:46:46.942+0000] {subprocess.py:93} INFO - 11:46:46
[2025-11-01T11:46:46.945+0000] {subprocess.py:93} INFO - 11:46:46  Concurrency: 4 threads (target='dev')
[2025-11-01T11:46:46.947+0000] {subprocess.py:93} INFO - 11:46:46
[2025-11-01T11:46:47.312+0000] {subprocess.py:93} INFO - 11:46:47  1 of 2 START sql incremental model `silver`.`silver_link_transactions` ......... [RUN]
[2025-11-01T11:46:47.314+0000] {subprocess.py:93} INFO - 11:46:47  2 of 2 START sql incremental model `silver`.`silver_payments` .................. [RUN]
[2025-11-01T11:46:47.510+0000] {subprocess.py:93} INFO - 11:46:47  1 of 2 ERROR creating sql incremental model `silver`.`silver_link_transactions`  [ERROR in 0.19s]
[2025-11-01T11:46:47.511+0000] {subprocess.py:93} INFO - 11:46:47  2 of 2 ERROR creating sql incremental model `silver`.`silver_payments` ......... [ERROR in 0.19s]
[2025-11-01T11:46:47.536+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.545+0000] {subprocess.py:93} INFO - 11:46:47  Finished running 2 incremental models in 0 hours 0 minutes and 0.59 seconds (0.59s).
[2025-11-01T11:46:47.741+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.752+0000] {subprocess.py:93} INFO - 11:46:47  Completed with 2 errors, 0 partial successes, and 0 warnings:
[2025-11-01T11:46:47.753+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.756+0000] {subprocess.py:93} INFO - 11:46:47  Failure in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:46:47.763+0000] {subprocess.py:93} INFO - 11:46:47    Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:46:47.769+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:46:47.772+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:46:47.775+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:46:47.776+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:46:47.777+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:46:47.778+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:46:47.779+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-11-01T11:46:47.782+0000] {subprocess.py:93} INFO -   > called by model silver_link_transactions (models/silver/silver_link_transactions.sql)
[2025-11-01T11:46:47.787+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.793+0000] {subprocess.py:93} INFO - 11:46:47    compiled code at target/compiled/ck_project/models/silver/silver_link_transactions.sql
[2025-11-01T11:46:47.799+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.801+0000] {subprocess.py:93} INFO - 11:46:47  Failure in model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:46:47.803+0000] {subprocess.py:93} INFO - 11:46:47    Compilation Error in model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:46:47.808+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:46:47.809+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:46:47.811+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:46:47.812+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:46:47.812+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:46:47.813+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:46:47.814+0000] {subprocess.py:93} INFO -   > called by macro materialization_incremental_clickhouse (macros/materializations/incremental/incremental.sql)
[2025-11-01T11:46:47.815+0000] {subprocess.py:93} INFO -   > called by model silver_payments (models/silver/silver_payments.sql)
[2025-11-01T11:46:47.816+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.817+0000] {subprocess.py:93} INFO - 11:46:47    compiled code at target/compiled/ck_project/models/silver/silver_payments.sql
[2025-11-01T11:46:47.818+0000] {subprocess.py:93} INFO - 11:46:47
[2025-11-01T11:46:47.819+0000] {subprocess.py:93} INFO - 11:46:47  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 NO-OP=0 TOTAL=2
[2025-11-01T11:46:48.891+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-11-01T11:46:48.913+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-11-01T11:46:48.919+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=silver_transformation_pipeline, task_id=dbt_run_incrementals, execution_date=20251030T000000, start_date=20251101T114639, end_date=20251101T114648
[2025-11-01T11:46:48.942+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task dbt_run_incrementals (Bash command failed. The command returned a non-zero exit code 1.; 1219)
[2025-11-01T11:46:48.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T11:46:49.015+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
