[2025-11-01T18:03:59.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T18:03:57.276509+00:00 [queued]>
[2025-11-01T18:03:59.570+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T18:03:57.276509+00:00 [queued]>
[2025-11-01T18:03:59.571+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T18:03:59.594+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_merchants> on 2025-11-01 18:03:57.276509+00:00
[2025-11-01T18:03:59.602+0000] {standard_task_runner.py:60} INFO - Started process 5142 to run task
[2025-11-01T18:03:59.608+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_merchants', 'manual__2025-11-01T18:03:57.276509+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpk4kkz7e6']
[2025-11-01T18:03:59.613+0000] {standard_task_runner.py:88} INFO - Job 109: Subtask dbt_run_merchants
[2025-11-01T18:03:59.711+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_merchants manual__2025-11-01T18:03:57.276509+00:00 [running]> on host 69cecc54c654
[2025-11-01T18:03:59.885+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T18:03:57.276509+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T18:03:57.276509+00:00'
[2025-11-01T18:04:04.660+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 191, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_merchants", ds=ds, full_refresh=True, pass_ds_lagged=False),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (2).
STDOUT:
18:04:02  Running with dbt=1.5.9
18:04:02  Registered adapter: clickhouse=1.5.2
18:04:02  Unable to do partial parsing because config vars, config profile, or config target have changed
18:04:03  Encountered an error:
Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
  No filter named 'ternary'.
    line 16
      | ternary(ch_drop_partition(this, ds_lagged), none)


STDERR:

[2025-11-01T18:04:04.680+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_merchants, execution_date=20251101T180357, start_date=20251101T180359, end_date=20251101T180404
[2025-11-01T18:04:04.696+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 109 for task dbt_run_merchants (dbt failed (2).
STDOUT:
18:04:02  Running with dbt=1.5.9
18:04:02  Registered adapter: clickhouse=1.5.2
18:04:02  Unable to do partial parsing because config vars, config profile, or config target have changed
18:04:03  Encountered an error:
Compilation Error in model silver_link_transactions (models/silver/silver_link_transactions.sql)
  No filter named 'ternary'.
    line 16
      | ternary(ch_drop_partition(this, ds_lagged), none)


STDERR:
; 5142)
[2025-11-01T18:04:04.711+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T18:04:04.732+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
