[2025-11-01T11:40:54.167+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-11-01T11:40:42.223946+00:00 [queued]>
[2025-11-01T11:40:54.208+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-11-01T11:40:42.223946+00:00 [queued]>
[2025-11-01T11:40:54.212+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T11:40:54.267+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): silver_dbt.dbt_run_merchants> on 2025-11-01 11:40:42.223946+00:00
[2025-11-01T11:40:54.281+0000] {standard_task_runner.py:60} INFO - Started process 531 to run task
[2025-11-01T11:40:54.289+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_pipeline', 'silver_dbt.dbt_run_merchants', 'manual__2025-11-01T11:40:42.223946+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpbtfw2i_4']
[2025-11-01T11:40:54.298+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask silver_dbt.dbt_run_merchants
[2025-11-01T11:40:54.517+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_pipeline.silver_dbt.dbt_run_merchants manual__2025-11-01T11:40:42.223946+00:00 [running]> on host 6ac9b46937d1
[2025-11-01T11:40:54.838+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_pipeline' AIRFLOW_CTX_TASK_ID='silver_dbt.dbt_run_merchants' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T11:40:42.223946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T11:40:42.223946+00:00'
[2025-11-01T11:40:54.844+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T11:40:54.847+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec -i dbt bash -lc 'cd /dbt && dbt --no-use-colors run --profiles-dir /dbt --select silver_merchants --full-refresh'"]
[2025-11-01T11:40:54.883+0000] {subprocess.py:86} INFO - Output:
[2025-11-01T11:41:00.297+0000] {subprocess.py:93} INFO - 11:41:00  Running with dbt=1.10.13
[2025-11-01T11:41:01.055+0000] {subprocess.py:93} INFO - 11:41:01  Registered adapter: clickhouse=1.9.5
[2025-11-01T11:41:01.693+0000] {subprocess.py:93} INFO - 11:41:01  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-11-01T11:41:06.095+0000] {subprocess.py:93} INFO - 11:41:06  Found 3 models, 3 sources, 491 macros
[2025-11-01T11:41:06.112+0000] {subprocess.py:93} INFO - 11:41:06
[2025-11-01T11:41:06.116+0000] {subprocess.py:93} INFO - 11:41:06  Concurrency: 4 threads (target='dev')
[2025-11-01T11:41:06.120+0000] {subprocess.py:93} INFO - 11:41:06
[2025-11-01T11:41:06.842+0000] {subprocess.py:93} INFO - 11:41:06  1 of 1 START sql table model `silver`.`silver_merchants` ....................... [RUN]
[2025-11-01T11:41:06.964+0000] {subprocess.py:93} INFO - 11:41:06  1 of 1 ERROR creating sql table model `silver`.`silver_merchants` .............. [ERROR in 0.11s]
[2025-11-01T11:41:07.023+0000] {subprocess.py:93} INFO - 11:41:07
[2025-11-01T11:41:07.029+0000] {subprocess.py:93} INFO - 11:41:07  Finished running 1 table model in 0 hours 0 minutes and 0.89 seconds (0.89s).
[2025-11-01T11:41:07.340+0000] {subprocess.py:93} INFO - 11:41:07
[2025-11-01T11:41:07.343+0000] {subprocess.py:93} INFO - 11:41:07  Completed with 1 error, 0 partial successes, and 0 warnings:
[2025-11-01T11:41:07.348+0000] {subprocess.py:93} INFO - 11:41:07
[2025-11-01T11:41:07.352+0000] {subprocess.py:93} INFO - 11:41:07  Failure in model silver_merchants (models/silver/silver_merchants.sql)
[2025-11-01T11:41:07.359+0000] {subprocess.py:93} INFO - 11:41:07    Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
[2025-11-01T11:41:07.360+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__clickhouse__create_table_as' takes not more than 2 argument(s)
[2025-11-01T11:41:07.361+0000] {subprocess.py:93} INFO - 
[2025-11-01T11:41:07.367+0000] {subprocess.py:93} INFO -   > in macro create_table_as (macros/relations/table/create.sql)
[2025-11-01T11:41:07.372+0000] {subprocess.py:93} INFO -   > called by macro default__get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:07.374+0000] {subprocess.py:93} INFO -   > called by macro get_create_table_as_sql (macros/relations/table/create.sql)
[2025-11-01T11:41:07.374+0000] {subprocess.py:93} INFO -   > called by macro statement (macros/etc/statement.sql)
[2025-11-01T11:41:07.377+0000] {subprocess.py:93} INFO -   > called by macro materialization_table_clickhouse (macros/materializations/table.sql)
[2025-11-01T11:41:07.378+0000] {subprocess.py:93} INFO -   > called by model silver_merchants (models/silver/silver_merchants.sql)
[2025-11-01T11:41:07.380+0000] {subprocess.py:93} INFO - 11:41:07
[2025-11-01T11:41:07.381+0000] {subprocess.py:93} INFO - 11:41:07    compiled code at target/compiled/ck_project/models/silver/silver_merchants.sql
[2025-11-01T11:41:07.411+0000] {subprocess.py:93} INFO - 11:41:07
[2025-11-01T11:41:07.413+0000] {subprocess.py:93} INFO - 11:41:07  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
[2025-11-01T11:41:08.761+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-11-01T11:41:08.789+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-11-01T11:41:08.797+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_pipeline, task_id=silver_dbt.dbt_run_merchants, execution_date=20251101T114042, start_date=20251101T114054, end_date=20251101T114108
[2025-11-01T11:41:08.823+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task silver_dbt.dbt_run_merchants (Bash command failed. The command returned a non-zero exit code 1.; 531)
[2025-11-01T11:41:08.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T11:41:08.920+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
