[2025-11-01T17:02:41.011+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T17:02:18.125002+00:00 [queued]>
[2025-11-01T17:02:41.028+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T17:02:18.125002+00:00 [queued]>
[2025-11-01T17:02:41.029+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-11-01T17:02:41.051+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run_linktx> on 2025-11-01 17:02:18.125002+00:00
[2025-11-01T17:02:41.060+0000] {standard_task_runner.py:60} INFO - Started process 962 to run task
[2025-11-01T17:02:41.066+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'silver_transformation_pipeline', 'dbt_run_linktx', 'manual__2025-11-01T17:02:18.125002+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/silver_dag.py', '--cfg-path', '/tmp/tmpu9eo46mx']
[2025-11-01T17:02:41.070+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask dbt_run_linktx
[2025-11-01T17:02:41.179+0000] {task_command.py:423} INFO - Running <TaskInstance: silver_transformation_pipeline.dbt_run_linktx manual__2025-11-01T17:02:18.125002+00:00 [running]> on host 69cecc54c654
[2025-11-01T17:02:41.309+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transformation_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_linktx' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T17:02:18.125002+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T17:02:18.125002+00:00'
[2025-11-01T17:02:45.872+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/silver_dag.py", line 176, in <lambda>
    python_callable=lambda ds, **_: _run_dbt("silver_link_transactions", ds=ds, full_refresh=False, pass_ds_lagged=True),
  File "/opt/airflow/dags/silver_dag.py", line 149, in _run_dbt
    raise RuntimeError(f"dbt failed ({proc.returncode}).\nSTDOUT:\n{proc.stdout}\n\nSTDERR:\n{proc.stderr}")
RuntimeError: dbt failed (2).
STDOUT:
17:02:44  Running with dbt=1.5.9
17:02:44  Registered adapter: clickhouse=1.5.2
17:02:45  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 2
      config(


STDERR:

[2025-11-01T17:02:45.899+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_transformation_pipeline, task_id=dbt_run_linktx, execution_date=20251101T170218, start_date=20251101T170241, end_date=20251101T170245
[2025-11-01T17:02:45.929+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task dbt_run_linktx (dbt failed (2).
STDOUT:
17:02:44  Running with dbt=1.5.9
17:02:44  Registered adapter: clickhouse=1.5.2
17:02:45  Encountered an error:
Compilation Error in model silver_merchants (models/silver/silver_merchants.sql)
  invalid syntax for function call expression
    line 2
      config(


STDERR:
; 962)
[2025-11-01T17:02:45.957+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T17:02:45.976+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
